### ISSUE TITLE
Allow setting alsa device name

### ISSUE THREAD

**Issue by ptrcnull** [haileys/bark#5]
currently, when `pactl` is unavailable, bark falls back to a "default audio device"; as such, it's not possible to explicitly specify an output device like `hw:0,2` when using pure alsa

**Comment by haileys** [comment]
[cpal](https://docs.rs/cpal/latest/cpal/), the audio library bark uses, does not support this unfortunately, hence the need for the env var based workaround. It's not ideal, and I would gladly accept pull requests improving on this situation, but it is not currently a priority to fix

**Comment by ptrcnull** [comment]
> it is not currently a priority to fix

why was it closed as completed then?

**Comment by ptrcnull** [comment]
how about just keeping it open?
